# Generated by Django 4.0.3 on 2022-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
