# Generated by Django 4.0.2 on 2022-03-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_educationentry_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationentry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='educationentry',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='start_date',
        ),
    ]
