# Generated by Django 4.0.2 on 2022-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_educationentry_end_date_educationentry_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
